jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.pull_request.user.type == 'User'}}
        uses: mtfoley/pr-compliance-action@main
        with:
          body-auto-close: false
          ignore-team-members: false

      - if: ${{ github.event.pull_request.user.type == 'Bot'}}
        run: echo "Compliance check skipped for bot PRs"

name: Compliance

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
