concurrency:
  group: Release
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore: release v')"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: kaisugi/action-regex-match@v1.0.2
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^chore: release v(\d+\.\d+\.\d+(?:-(?:alpha|beta|rc)\.\d+)?)(?: \(#\d+\))?(?:\n|$)'
          flags: "su"

      - if: steps.regex-match.outputs.match != ''
        id: release_version
        run: echo "release_version=${{ steps.regex-match.outputs.group1 }}" >> "$GITHUB_OUTPUT"

      - if: steps.release_version.outputs.release_version != ''
        uses: ./.github/actions/prepare

      - if: steps.release_version.outputs.release_version != ''
        name: Build
        run: pnpm run build

      - if: steps.release_version.outputs.release_version != ''
        name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pnpm dlx release-it --npm.allowSameVersion -i ${{ steps.release_version.outputs.release_version }}

name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
