concurrency:
  cancel-in-progress: true
  group: Prepare Release ${{ github.ref_name }}

jobs:
  release_pr:
    if: "!startsWith(github.event.head_commit.message, 'chore: release v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/prepare

      - run: pnpm build

      - id: should_release
        run: echo "should_release=$(pnpm run should-semantic-release &> /dev/null && pnpm run lint:package &> /dev/null && echo '1' || echo '0')" >> "$GITHUB_OUTPUT"

      - env:
          GITHUB_TOKEN: ${{ github.token }}
        if: steps.should_release.outputs.should_release != '0'
        run: pnpm dlx release-it --no-git.push --no-npm.publish --no-github.release --no-gitlab.release

      - if: steps.should_release.outputs.should_release != '0'
        name: Generate Docs
        run: pnpm run docs

      - if: steps.should_release.outputs.should_release != '0'
        name: Update Coverage Badge
        run: cp ./docs/generated/coverage.svg ./docs/coverage.svg

      - id: package-version
        if: steps.should_release.outputs.should_release != '0'
        name: Get Release Version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - env:
          RELEASE_VERSION: ${{ steps.package-version.outputs.current-version }}
        if: steps.should_release.outputs.should_release != '0' && steps.package-version.outputs.current-version != ''
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v8.1.0
        with:
          assignees: ${{ github.actor }}
          base: ${{ github.ref_name }}
          body: Merge this PR to release v${{ env.RELEASE_VERSION }}
          branch: release/${{ github.ref_name }}
          commit-message: "chore: release v${{ env.RELEASE_VERSION }}"
          delete-branch: true
          sign-commits: true
          title: "chore: release v${{ env.RELEASE_VERSION }}"
          token: ${{ github.token }}

name: Create Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
