jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node_version }}

      - run: pnpm remove typescript
      - run: pnpm add -D typescript@"${{ matrix.ts_version }}"

      - run: pnpm run test --coverage
      - if: matrix.node_version == '22.x'
        name: Codecov
        uses: codecov/codecov-action@v6
        with:
          flags: ${{ matrix.ts_version }}

    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 20.x
          - 22.x
          - 24.x
          - latest
        ts_version:
          - 5.5.4
          - 5.9.3
          - latest

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
